name: Build Aseprite (Release)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 120
    steps:
    - name: Checkout Aseprite
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Cache Skia
      id: cache-skia
      uses: actions/cache@v4
      with:
        path: skia
        key: skia-windows-x64-${{ hashFiles('laf/misc/skia-url.sh') }}

    - name: Install Skia
      if: steps.cache-skia.outputs.cache-hit != 'true'
      shell: bash
      run: |
        this_dir=$(cygpath "${{ github.workspace }}")
        skia_url=$(source $this_dir/laf/misc/skia-url.sh | xargs)
        skia_file=$(basename $skia_url)
        echo "正在下载 Skia: $skia_url"
        curl --ssl-revoke-best-effort -L -o "$skia_file" "$skia_url"
        unzip "$skia_file" -d skia

    - name: Set up Ninja
      uses: aseprite/get-ninja@main

    - name: Set up MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64

    - name: Generating Makefiles
      shell: bash
      run: |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DENABLE_TESTS=OFF \
          -DENABLE_SCRIPTING=ON \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=$(realpath skia) \
          -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-x64)

    - name: Compiling
      shell: bash
      run: |
        cd build && ninja -j1 aseprite

    - name: Create Release Package
      shell: cmd
      run: |
        mkdir dist
        copy build\bin\aseprite.exe dist\
        xcopy /E /I build\bin\data dist\data
        powershell Compress-Archive -Path dist\* -DestinationPath aseprite-windows.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-windows
        path: aseprite-windows.zip    
        with:arch: x64

    - name: Generating Makefiles
      shell: bash
      run: |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DENABLE_TESTS=OFF \
          -DENABLE_SCRIPTING=ON \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=$(realpath skia) \
          -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-x64)

    - name: Compiling
      shell: bash
      run: |
        cd build && ninja -j2 aseprite

    - name: Create Release Package
      run: |
        mkdir dist
        copy build\bin\aseprite.exe dist\
        xcopy /E /I build\bin\data dist\data
        powershell Compress-Archive -Path dist\* -DestinationPath aseprite-windows.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-windows
        path: aseprite-windows.zip  
        
